# Generated by Django 5.0.3 on 2024-04-05 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_commentreply_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreply',
            name='book',
        ),
    ]
