# Generated by Django 5.0.3 on 2024-04-06 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_delete_comment'),
        ('comments', '0008_alter_commentreply_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreply',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='books.book'),
        ),
    ]
