# Generated by Django 5.0.3 on 2024-04-13 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_commentlike_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlike',
            name='likes_count',
        ),
    ]
