# Generated by Django 5.0.3 on 2024-04-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0012_remove_commentlike_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
