# Generated by Django 5.0.3 on 2024-03-21 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
