# Generated by Django 5.0.3 on 2024-03-12 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_is_staff_profile_is_moderator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_moderator',
        ),
    ]
